### ISSUE TITLE
Needed --no-same-owner on tar

### ISSUE THREAD

**Issue by larsimmisch** [hifiberry/dacadckernel#1]
The command:
```
sudo tar xvzf ~/dacadckernel/4.18.dacadc.tar.gz
```
Failed with lots of:
```
Cannot change ownership to uid 1000, gid 1000: Operation not permitted
```

I suspect this has to do with how `/boot` is mounted. I avoided the errors by using:
```
 sudo tar xvzf ~/dacadckernel/4.18.dacadc.tar.gz --no-same-owner
```

**Comment by hifiberry** [comment]
I've added this to the script, but I don't have a test system here at the moment. Can you try again?

**Comment by larsimmisch** [comment]
That line does work on my Pi.

**Comment by larsimmisch** [comment]
But I should note that the line:
```
cd /home/pi
```

will not work for me because I'm using a user different from `pi`. 

A simple `cd` should be sufficient, though.

**Comment by hifiberry** [comment]
Done
